import {
  Award,
  Bell,
  BookOpen,
  Building2,
  Calendar,
  ClipboardList,
  Clock,
  Database,
  FileCheck2,
  FileSpreadsheet,
  FileText,
  Folder,
  FolderOpen,
  GraduationCap,
  KeyRound,
  Layers,
  LayoutDashboard,
  Leaf,
  Library,
  ListChecks,
  Mail,
  MessageSquare,
  Printer,
  School,
  Settings,
  Settings2,
  Shield,
  TrendingUp,
  Trophy,
  UserCheck,
  Users,
  Wallet,
  type LucideIcon,
} from "lucide-react"
import { isMenuIconName, type MenuIconName } from "@/lib/menu-icon-names"

// Record<MenuIconName, ...> memaksa daftar ini sama persis dengan MENU_ICON_NAMES
export const MENU_ICONS: Record<MenuIconName, LucideIcon> = {
  LayoutDashboard,
  Database,
  FileText,
  FileCheck2,
  ClipboardList,
  ListChecks,
  FileSpreadsheet,
  BookOpen,
  Library,
  GraduationCap,
  School,
  Users,
  UserCheck,
  Settings,
  Settings2,
  Shield,
  KeyRound,
  Layers,
  Folder,
  FolderOpen,
  Calendar,
  Clock,
  TrendingUp,
  Award,
  Trophy,
  Printer,
  Mail,
  Bell,
  MessageSquare,
  Building2,
  Wallet,
  Leaf,
}

export function getMenuIcon(name: string | null | undefined): LucideIcon | null {
  return isMenuIconName(name) ? MENU_ICONS[name] : null
}